### PR TITLE
Adds new HospitalRun logos

### PR DESCRIPTION
**Pull request by matteovivona**
In restyling of the logo, made by @StefanoMic, we decided to use a white and a dark variant.

Cc @fox1t @lauggh

### CODE REVIEW

**Comment by brianwarner** [comment]
Thanks!  These logos look great.  Can you please push one more commit that keeps the color descriptions consistent, both in the README table and the filenames?  Looks like the first one called "white" should be "color, dark background" and the other should be just "color".

I have been using "white" for all-white monochrome variants, "black" for all-black monochrome variants, and "grayscale" for desaturated variants.

**Comment by matteovivona** [comment]
ok no problem! unfortunately, our variants don't have a "dark background", so I didn't know how to name it

**Comment by brianwarner** [comment]
It's all good, most of them don't.  The description is meant to mean "(This logo can be used on a) dark background."  

I appreciate you doing this!

**Comment by brianwarner** [comment]
Thanks @tehKapa!

**Pull request merged**
